spring.application.name=escritorio

spring.datasource.url=jdbc:mysql://localhost:3306/escritorio?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Nobu2016.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true